### ISSUE TITLE
errors on small data with small abs error bound

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#9]
I updated [sztest](https://github.com/bd4/sztest) to take rows/cols/abs bound exp as args. I get the following errors:

```
./sztest-static 16 17 -5
size 16x17, 2176 bytes
[SZ] Reading SZ configuration file (sz.config) ...

== RAND ==
out_size = -5 (-0.0023)
out = 0x1998d20
abs bound = 0.0000100000000000
Error: zlib_uncompress2: stream.avail_in != cmpSizeWrong version: 
Compressed-data version (0.0.0)
Current sz version: (1.4.9)
```
This also happens for smaller values of rows/cols.

If I go larger, I get a segfault:
```
./sztest-static 17 17 -5
size 17x17, 2312 bytes
[SZ] Reading SZ configuration file (sz.config) ...

== RAND ==
out_size = 1302 (0.5631)
out = 0x1d99f70
abs bound = 0.0000100000000000
Segmentation fault (core dumped)
```

Here is a backtrace for the segfault:
```
Program received signal SIGSEGV, Segmentation fault.
decode (out=0x11cf330, t=0x73f2f0, targetLength=289, s=0x6499cc "\377\177")
    at src/Huffman.c:275
275			if (n->t) {
(gdb) backtrace
#0  decode (out=0x11cf330, t=0x73f2f0, targetLength=289, s=0x6499cc "\377\177")
    at src/Huffman.c:275
#1  decode_withTree (s=0x6499c0 "", targetLength=289, out=0x11cf330)
    at src/Huffman.c:671
#2  0x0000000000404fe9 in decompressDataSeries_double_2D (data=0x7fffffffca88, 
    r1=17, r2=17, tdps=0x649920) at src/TightDataPointStorageD.c:364
#3  0x0000000000408b1c in getSnapshotData_double_2D (
    data=data@entry=0x7fffffffca88, r1=r1@entry=17, r2=r2@entry=17, 
    tdps=tdps@entry=0x649920, errBoundMode=errBoundMode@entry=0)
    at src/TightDataPointStorageD.c:1256
#4  0x000000000041a3f5 in SZ_decompress_args_double (
    newData=newData@entry=0x7fffffffca88, r5=<optimized out>, r4=0, 
    r3=r3@entry=0, r2=r2@entry=17, r1=r1@entry=17, cmpBytes=<optimized out>, 
    cmpSize=1302) at src/sz_double.c:1107
#5  0x0000000000401f54 in SZ_decompress (r1=17, r2=17, r3=0, 
    r4=<optimized out>, r5=<optimized out>, byteLength=<optimized out>, 
    bytes=<optimized out>, dataType=1) at src/sz.c:369
#6  SZ_decompress_args (dataType=<optimized out>, bytes=<optimized out>, 
    byteLength=<optimized out>, decompressed_array=0x649010, 
    r5=<optimized out>, r4=<optimized out>, r3=0, r2=17, r1=17) at src/sz.c:394
#7  0x0000000000401732 in test_roundtrip (data=0x647420, n=289, 
    abs_bound=1.0000000000000001e-05, r5=0, r4=0, r3=0, r2=17, r1=17)
    at sztest.c:125
```

**Comment by bd4** [comment]
Thanks, fixed in latest github source.
